#!/usr/bin/env python3
"""Analyse every scenario setup (NN_*.json) of this folder and write, next to it, the raw analysis
(NN_*.analysis.json) and the interactive report (NN_*.report.html), plus index.html with an overview.

    python3 generate.py            all scenarios
    python3 generate.py 05 09      only those whose file name starts with these numbers
    python3 generate.py --images   with pictures of the signing devices (attribution required, see Lookups/DeviceImages.csv)
"""
import html
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent / "engine"))

import analyze  # noqa: E402
import report   # noqa: E402
import loader   # noqa: E402


def main(argv):
    images = "--images" in argv
    wanted = {a for a in argv if a != "--images"}
    setups = sorted(p for p in HERE.glob("[0-9][0-9]_*.json") if not p.name.endswith(".analysis.json"))
    for path in setups:
        if wanted and path.name[:2] not in wanted:
            continue
        result = analyze.analyze(path)
        if result.get("errors"):
            print(path.name, "ERRORS", *result["errors"], sep="\n  ")
            continue
        analyze.write_raw(result, path.with_suffix(".analysis.json"))
        report.write_html(result, path, path.with_suffix(".report.html"), images=images)
        print(path.name, len(result["rows"]), "rows", len(result["warnings"]), "warnings")
    write_index(setups)


def write_index(setups):
    rows = []
    for path in setups:
        out = path.with_suffix(".analysis.json")
        if not out.exists():
            continue
        data = loader.read_json(out)
        setup = loader.read_json(path)
        risks = Counter(r["R"] for r in data["rows"])
        dist = " ".join(f"<span class='r{k}'>{risks.get(k, 0)}</span>" for k in (4, 3, 2, 1, 0))
        warn = "".join(f"<li>{html.escape(w)}</li>" for w in data["warnings"])
        rows.append(f"<tr><td><b>{html.escape(setup['name'])}</b><br><small>{html.escape(path.name)}</small></td>"
                    f"<td>{html.escape(setup.get('comment', ''))}</td><td class='n'>{len(data['rows'])}</td><td>{dist}</td>"
                    f"<td><ul>{warn}</ul></td>"
                    f"<td><a href='{path.with_suffix('.report.html').name}'>report</a><br>"
                    f"<a href='{path.name}'>setup</a><br><a href='{out.name}'>analysis</a></td></tr>")
    page = """<!doctype html><meta charset="utf-8"><title>Scenarios</title>
<style>body{font:13px system-ui,sans-serif;margin:16px}table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:4px 8px;vertical-align:top}
.r0{background:#c8e6c9}.r1{background:#e6ee9c}.r2{background:#ffe082}.r3{background:#ffab91}.r4{background:#ef5350;color:#fff}
span[class^=r]{display:inline-block;min-width:1.8em;text-align:center;border-radius:3px;margin-right:2px}td.n{text-align:right}ul{margin:0;padding-left:16px}</style>
<h1>Scenarios, from simple to complex</h1>
<p>Risk columns: critical, high, medium, low, negligible (number of lines). Generated by generate.py.</p>
<table><tr><th>Scenario</th><th>What to look at</th><th>Lines</th><th>Risk 4 to 0</th><th>Warnings</th><th>Open</th></tr>""" + "\n".join(rows) + "</table>"
    (HERE / "index.html").write_text(page, encoding="utf-8")
    print("index.html written")


if __name__ == "__main__":
    main(sys.argv[1:])
